# Generated by Django 4.2.16 on 2024-12-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_docente_alter_curso_options_alter_curso_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.AlterModelTable(
            name='curso',
            table=None,
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
