# Generated by Django 4.2.16 on 2024-12-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_docente_curso_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
